### ISSUE TITLE
Can't resolve dependency  

### ISSUE THREAD

**Issue by bblia** [androidessence/RecyclerViewCursorAdapter#3]
Getting "Could not find com.androidessence:recyclerviewcursoradapter:1.0.0." when compiling now. Looks like it's not hosted anymore :( Any chance you could throw it back up on jcenter? This adapter has been a lifesaver!

**Comment by bblia** [comment]
I can also just import it manually if you're over maintaining it :)

**Comment by SureshCS-50** [comment]
Ya.. I am facing the same issue.. :(

**Comment by AdamMc331** [comment]
Sorry all! I am not sure why this happened. I have resubmit the jcenter request. In the mean time, you can also reference my maven repository in your build.gradle file and that should resolve the issue, because it is in my bintray account still:

```java
    repositories {
        maven {
            url  "http://dl.bintray.com/androidessence/maven"
        }
    }
```

**Comment by AdamMc331** [comment]
@SureshCS-50 @bblia 

Just got an email from Jcenter, it should be good again, worked for me. Closing ticket, feel free to reopen if you're still seeing issues.

**Comment by bblia** [comment]
@AdamMc331 thank you!

**Comment by AdamMc331** [comment]
No problem! So sorry I didn't see your original messenger in September, I'm glad bblia commented this morning to bring it to my attention. I'm glad this is working for you, and let me know if there are any other ways I can improve it!

**Comment by bblia** [comment]
after i commented I actually ended up just forking it locally, but if i ever end up making changes i'll definitely pull request! Thanks for writing this, it was a huge help.

**Comment by AdamMc331** [comment]
Of course! I wrote it because I was in demand for it myself, and then it just got away from me. I haven't touched my other project in a while, so I never caught this issue hahaha.
